[build]
  command = "dotnet publish -c Release -o ./publish"
  publish = "publish/wwwroot"  # The output directory of your app after publishing

# Optional: You can define environment variables, add caching, etc.
