[build]
  command = "wget https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-8.0.0-preview.8-linux-x64-binaries -O dotnet.tar.gz && tar -xvf dotnet.tar.gz && export PATH=$PATH:$(pwd)/dotnet && dotnet publish -c Release -o ./publish"
  publish = "publish/wwwroot"
